server:
 port: 8081
 
spring:
    application:
      name: 'fornecedor'

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka